mixin () {
  public query func getApiDoc() : async Text {
    let doc = "# NJM Enterprises Vehicle Inventory API\n\n"
      # "## Purpose\n"
      # "Backend for the NJM Enterprises premium automotive dealership website. Maintains a public catalog of vehicles (Roll On Roll Off and Brand New) and accepts customer inquiries. Prices are quoted in Trinidad and Tobago Dollars (TT$).\n\n"
      # "## Public Methods\n\n"
      # "### Vehicle catalog\n"
      # "- `listVehicles() : async [Vehicle]` — query. Returns every vehicle in the catalog.\n"
      # "- `getVehicle(stockId : Text) : async ?Vehicle` — query. Returns the vehicle with the given `stockId`, or `null` if none exists.\n"
      # "- `listVehiclesByMake(make : Text) : async [Vehicle]` — query. Returns all vehicles whose `make` matches (case-sensitive exact match).\n\n"
      # "### Inquiries\n"
      # "- `submitInquiry(inquiry : Inquiry) : async ()` — update. Records a customer inquiry. Callable by any caller.\n\n"
      # "### OQL (Data Intelligence)\n"
      # "- `schema() : async Text` — query. Returns the JSON schema of the queryable entities.\n"
      # "- `execute(qJson : Text) : async Result` — query. Executes an OQL query. Traps with `OQL: invalid query — <detail>` on malformed query JSON.\n\n"
      # "### Documentation\n"
      # "- `getApiDoc() : async Text` — query. Returns this document.\n\n"
      # "### Authentication and authorization\n"
      # "- `_internet_identity_sign_in_start() : async Blob` — update. Begins an Internet Identity sign-in challenge.\n"
      # "- `_internet_identity_sign_in_finish() : async Result.Result<(), Error>` — update. Completes sign-in and registers the caller.\n"
      # "- `_initialize_access_control() : async ()` — update. Registers the caller as a user. The first caller to initialize becomes admin.\n"
      # "- `getCallerUserRole() : async UserRole` — query. Returns the caller's role (`#admin`, `#user`, or `#guest`).\n"
      # "- `assignCallerUserRole(user : Principal, role : UserRole) : async ()` — update. Admin-only. Assigns a role to a user.\n"
      # "- `isCallerAdmin() : async Bool` — query. Returns whether the caller is an admin.\n\n"
      # "## Authentication and identity\n"
      # "The app uses Internet Identity. The frontend pins an Internet Identity derivation origin, published at `/.well-known/ii-derivation-origin` when available. An agent already holding the user's Internet Identity authorization derives the correct per-app principal against that origin, for example `icp identity link web <name> --app <host>`. Such a delegation acts with the user's full authority in this app until it expires.\n\n"
      # "### Registration\n"
      # "Registration happens only when a caller signs in through the app's own frontend. A direct API caller can register by calling `_initialize_access_control` once as a signed-in caller before any role-guarded call (guarded queries included). The first initializer receives the `#admin` role; subsequent callers receive `#user`. An anonymous caller is treated as `#guest`. A caller can be unregistered even when it belongs to the app's owner, because registration only occurs through the frontend sign-in flow; a signed-in caller derived against a different origin is a different principal than the one the frontend registered.\n\n"
      # "## Authorization\n"
      # "- The vehicle catalog (`vehicle` entity) is public: any caller, including anonymous, can read it through `listVehicles`, `getVehicle`, `listVehiclesByMake`, and OQL.\n"
      # "- Inquiries (`inquiry` entity) are controller-only: only the platform controller (and the Data Intelligence agent) can read them through OQL. End users cannot read inquiries.\n"
      # "- Role-guarded methods (`assignCallerUserRole`) require a signed-in admin caller.\n\n"
      # "## Units and encodings\n"
      # "- Prices are in TT$ (Trinidad and Tobago Dollar). `price : ?Nat` is the price in whole TT$; `null` means price on application (use `priceLabel` for display). `priceLabel : Text` is a human-readable price string (e.g. \"POA\").\n"
      # "- `createdAt : Int` is nanoseconds since the Unix epoch.\n"
      # "- `stockId : Text` is the vehicle's stock identifier.\n"
      # "- `condition` is a variant: `#BrandNew` or `#Roro`.\n"
      # "- `bodyType` is a variant: `#SUV`, `#Sedan`, `#Hatchback`, `#Van`, `#Coupe`, or `#Wagon`.\n"
      # "- `featured : Bool` marks a vehicle for featured display.\n\n"
      # "## Lifecycle and polling\n"
      # "All operations are immediate; there are no long-running jobs. No polling is required. Queries return the current state.\n\n"
      # "## Mutation retry safety\n"
      # "`submitInquiry` appends a new inquiry each time it is called; it is not idempotent, so retrying a failed submission may create duplicate inquiries. There are no destructive operations.\n\n"
      # "## Errors and gotchas\n"
      # "- OQL `execute` traps with `OQL: invalid query — <detail>` on malformed query JSON.\n"
      # "- Authorization failures trap with an `Unauthorized` message.\n"
      # "- `query` is a reserved keyword in Motoko, so the OQL query method is named `execute`.\n"
      # "- The vehicle catalog is world-readable; inquiries are private to the platform.\n";
    doc
  };
};
