/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const BodyType = IDL.Variant({
  'SUV' : IDL.Null,
  'Van' : IDL.Null,
  'Sedan' : IDL.Null,
  'Wagon' : IDL.Null,
  'Hatchback' : IDL.Null,
  'Coupe' : IDL.Null,
});
export const Condition = IDL.Variant({
  'Roro' : IDL.Null,
  'BrandNew' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'model' : IDL.Text,
  'featured' : IDL.Bool,
  'stockId' : IDL.Text,
  'make' : IDL.Text,
  'trim' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'colour' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
  'bodyType' : BodyType,
  'condition' : Condition,
  'priceLabel' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'vehicleOfInterest' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getVehicle' : IDL.Func([IDL.Text], [IDL.Opt(Vehicle)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'listVehiclesByMake' : IDL.Func([IDL.Text], [IDL.Vec(Vehicle)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'submitInquiry' : IDL.Func([Inquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const BodyType = IDL.Variant({
    'SUV' : IDL.Null,
    'Van' : IDL.Null,
    'Sedan' : IDL.Null,
    'Wagon' : IDL.Null,
    'Hatchback' : IDL.Null,
    'Coupe' : IDL.Null,
  });
  const Condition = IDL.Variant({ 'Roro' : IDL.Null, 'BrandNew' : IDL.Null });
  const Vehicle = IDL.Record({
    'model' : IDL.Text,
    'featured' : IDL.Bool,
    'stockId' : IDL.Text,
    'make' : IDL.Text,
    'trim' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'colour' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
    'bodyType' : BodyType,
    'condition' : Condition,
    'priceLabel' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'vehicleOfInterest' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getVehicle' : IDL.Func([IDL.Text], [IDL.Opt(Vehicle)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'listVehiclesByMake' : IDL.Func([IDL.Text], [IDL.Vec(Vehicle)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'submitInquiry' : IDL.Func([Inquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };