/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BodyType = { 'SUV' : null } |
  { 'Van' : null } |
  { 'Sedan' : null } |
  { 'Wagon' : null } |
  { 'Hatchback' : null } |
  { 'Coupe' : null };
export interface Cell { 'value' : Value, 'name' : string }
export type Condition = { 'Roro' : null } |
  { 'BrandNew' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Inquiry {
  'vehicleOfInterest' : string,
  'name' : string,
  'createdAt' : bigint,
  'message' : string,
  'phone' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Vehicle {
  'model' : string,
  'featured' : boolean,
  'stockId' : string,
  'make' : string,
  'trim' : string,
  'year' : bigint,
  'description' : string,
  'imageUrl' : string,
  'colour' : string,
  'price' : [] | [bigint],
  'bodyType' : BodyType,
  'condition' : Condition,
  'priceLabel' : string,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getVehicle' : ActorMethod<[string], [] | [Vehicle]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listVehicles' : ActorMethod<[], Array<Vehicle>>,
  'listVehiclesByMake' : ActorMethod<[string], Array<Vehicle>>,
  'schema' : ActorMethod<[], string>,
  'submitInquiry' : ActorMethod<[Inquiry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];